# Site Settings
title:               IDLI
tagline:             India Deep Learning Initiative
description:
baseurl:            "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io"
url:                "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io"
github:          
url:               "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io "
author:              "IDLI"
name:              "IDLI"
email:             "indiadeeplearning.group@gmail.com"
twitter:           "IDLI"
instagram:         "IDLI"
facebook:          "https://www.facebook.com/groups/1479309132086977/"
linkedin:          "IDLI"
paginate:            5
disqus:            digitaldrummerj

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems: [jekyll-paginate]

collections:
   jobs:
     output: true
     permalink: /jobs/
   internship:
     output: true
     permalink: /internship/
   tutorial:
     output: true
     permalink: /tutorial/
   interview:
     output: true
     permalink: /interview/
   dataset:
     output: true
     permalink: /dataset/:path/
   framework:
     output: true
     permalink: /framework/
   papers:
     output: true
     permalink: /papers/
   challenges:
     output: true
     permalink: /challenges/
   session:
     output: true
     permalink: /session/:path/
   hackthaone:
     output: true
     permalink: /hackthaone/:path/







    
