# Site Settings
title:               IDLI
tagline:             India Deep Learning Initiative
description:
baseurl:            "http://idli.group"
url:                "http://idli.group"
github:          
url:               "http://idli.group"
author:              "IDLI"
name:              "IDLI"
email:             "indiadeeplearning.group@gmail.com"
twitter:           "IDLI"
instagram:         "IDLI"
facebook:          "https://www.facebook.com/groups/1479309132086977/"
linkedin:          "IDLI"
paginate:            5
disqus:            digitaldrummerj

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems: [jekyll-paginate]

collections:
   jobs:
     output: true
     permalink: /jobs/:path/
   internship:
     output: true
     permalink: /internship/:path/
   tutorial:
     output: true
     permalink: /tutorial/:path/
   interview:
     output: true
     permalink: /interview/:path/
   dataset:
     output: true
     permalink: /dataset/:path/
   framework:
     output: true
     permalink: /framework/:path/
   papers:
     output: true
     permalink: /papers/:path/
   challenges:
     output: true
     permalink: /challenges/:path/
   session:
     output: true
     permalink: /session/:path/
   hackthaone:
     output: true
     permalink: /hackthaone/:path/
   upcomming:
     output: true
     permalink: /upcomming/:path/ 







    
