# Site Settings
title:               IDLI
tagline:             India Deep Learning Initiative
description:
baseurl:            "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io"
url:                "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io"
github:
url:               "https://github.com/IndiaDeepLearningInitiative-IDLI/IndiaDeepLearningInitiative-IDLI.github.io "
author:              "IDLI"
name:              "IDLI"
email:             "indiadeeplearning.group@gmail.com"
twitter:           "IDLI"
instagram:         "IDLI"
facebook:          "IDLI"
linkedin:          "IDLI"
paginate:            5


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems: [jekyll-paginate]
